<#
.SYNOPSIS
Creates a starter DBA script file for a requested task.

.DESCRIPTION
This helper scaffolds a simple SQL script template in the appropriate category folder based on a task keyword.
It reduces setup time when you want a new DBA script quickly.
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$Task,

    [string]$Category = 'performance-troubleshooting',
    [string]$Type = 'sql'
)

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..\..')
$targetDir = Join-Path $repoRoot "categories/$Category/$Type"

if (-not (Test-Path -LiteralPath $targetDir)) {
    New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
}

$slug = ($Task -replace '\W+', '-').Trim('-').ToLowerInvariant()
$fileName = "Get-{0}.sql" -f ((Get-Culture).TextInfo.ToTitleCase($slug) -replace '-', '')
$fullPath = Join-Path $targetDir $fileName

if (Test-Path -LiteralPath $fullPath) {
    Write-Warning "File already exists: $fullPath"
    return
}

$script = @"
-- DBA starter script for: $Task
-- Generated by helpers/scaffolding/Generate-NextScript.ps1

SELECT GETDATE() AS generated_at, '$Task' AS task_name;
"@

Set-Content -LiteralPath $fullPath -Value $script -Encoding UTF8
Write-Host "Created starter script: $fullPath" -ForegroundColor Green
