"""Freshness contract: the shipped datasets must still agree with their sources.

The datasets under src/sqldba_mcp/datasets/ are GENERATED. A hand-edit, or a source that
changed without a re-export, makes the server cite a script or a post that no longer says
what it claims - and nothing about that failure is visible at runtime. It has to break the
build instead.

What this can and cannot prove, stated honestly:

  scripts.json / docs.json / prompts.json  derive from files IN THIS REPO, so CI re-derives
                                           them and compares byte for byte. Exact.
  errors / waits / faqs / builds           derive from sqldba.blog and a private generator
                                           that CI cannot run. Only the age stamp and
                                           internal consistency can be checked here; the
                                           full check is `export-mcp-data.py --check`,
                                           run where those sources exist.

    python tests/check_freshness.py          # CI gate, exit 1 on drift
    python tests/check_freshness.py --warn   # report only, never fail

Console output is ASCII-only (cp1252 consoles die on anything else).
"""
from __future__ import annotations

import datetime
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]                      # dba-tools/
DATASETS = HERE.parent / 'src' / 'sqldba_mcp' / 'datasets'

# Post-derived data is regenerated by hand from the blog; this is the age at which the
# server starts warning in its own answers (mirrors data.STALE_AFTER_DAYS).
STALE_AFTER_DAYS = 90
WARN_ONLY = '--warn' in sys.argv

problems: list[str] = []
notes: list[str] = []


def load(name: str):
    return json.loads((DATASETS / ('%s.json' % name)).read_text(encoding='utf-8'))


def check_scripts() -> None:
    """Every shipped script body must match the file it came from, byte for byte."""
    shipped = {s['path']: s for s in load('scripts')}

    on_disk = set()
    for p in REPO.glob('sql/**/*.sql'):
        on_disk.add(p.relative_to(REPO).as_posix())
    for p in REPO.glob('powershell/**/*.ps1'):
        rel = p.relative_to(REPO)
        if 'wrappers' in rel.parts or 'lab' in rel.parts:
            continue
        on_disk.add(rel.as_posix())

    missing = sorted(on_disk - set(shipped))
    extra = sorted(set(shipped) - on_disk)
    if missing:
        problems.append('%d script(s) in the repo are NOT in scripts.json (re-export): %s'
                        % (len(missing), ', '.join(missing[:4])))
    if extra:
        problems.append('%d script(s) in scripts.json no longer exist in the repo: %s'
                        % (len(extra), ', '.join(extra[:4])))

    drifted = []
    for rel, record in shipped.items():
        path = REPO / rel
        if not path.exists():
            continue
        if path.read_text(encoding='utf-8', errors='replace') != record['body']:
            drifted.append(rel)
    if drifted:
        problems.append('%d script body/bodies differ from the repo (re-export): %s'
                        % (len(drifted), ', '.join(sorted(drifted)[:4])))
    notes.append('scripts: %d shipped, %d on disk, %d drifted'
                 % (len(shipped), len(on_disk), len(drifted)))


def check_docs_and_prompts() -> None:
    drifted = []
    for d in load('docs'):
        path = REPO / d['path']
        if not path.exists():
            problems.append('doc source missing: %s' % d['path'])
            continue
        if path.read_text(encoding='utf-8', errors='replace') != d['body']:
            drifted.append(d['path'])
    for p in load('prompts'):
        path = REPO / p['source']
        if not path.exists():
            problems.append('prompt source missing: %s' % p['source'])
            continue
        if path.read_text(encoding='utf-8', errors='replace') != p['body']:
            drifted.append(p['source'])
    if drifted:
        problems.append('%d doc/prompt body/bodies differ from the repo (re-export): %s'
                        % (len(drifted), ', '.join(sorted(drifted))))
    notes.append('docs+prompts: %d checked, %d drifted'
                 % (len(load('docs')) + len(load('prompts')), len(drifted)))


def check_counts() -> None:
    meta = load('_meta')
    c = meta.get('counts', {})
    actual = {
        'errors': len(load('errors')), 'waits': len(load('waits')),
        'faqs': len(load('faqs')), 'scripts': len(load('scripts')),
        'docs': len(load('docs')), 'prompts': len(load('prompts')),
        'versions': len(load('builds')['versions']),
    }
    for key, n in actual.items():
        if c.get(key) != n:
            problems.append('_meta count %s says %s, actual %s' % (key, c.get(key), n))
    notes.append('counts: %s' % ', '.join('%s=%d' % kv for kv in sorted(actual.items())))


def check_age() -> None:
    meta = load('_meta')
    stamp = meta.get('generated')
    if not stamp:
        problems.append('_meta has no `generated` stamp')
        return
    age = (datetime.date.today() - datetime.date.fromisoformat(stamp)).days
    notes.append('post-derived data generated %s (%d days old)' % (stamp, age))
    if age > STALE_AFTER_DAYS:
        # Not a build failure: the blog is the source of truth and it changes on Peter's
        # schedule, not CI's. The server already warns in its own answers past this age.
        notes.append('NOTE: past the %d-day threshold - the server now warns in its own '
                     'check_build answers. Re-run export-mcp-data.py.' % STALE_AFTER_DAYS)


def check_urls() -> None:
    bad = []
    for name, rows in (('errors', load('errors')), ('faqs', load('faqs')),
                       ('waits', load('waits'))):
        for r in rows:
            url = r.get('url')
            if url and not re.match(r'^https://sqldba\.blog/[a-z0-9\-/]+/$', url):
                bad.append('%s: %s' % (name, url))
    if bad:
        problems.append('%d malformed source URL(s): %s' % (len(bad), ', '.join(bad[:3])))


def main() -> int:
    for check in (check_scripts, check_docs_and_prompts, check_counts,
                  check_age, check_urls):
        check()

    for n in notes:
        print('  %s' % n)
    if not problems:
        print('FRESHNESS OK - datasets agree with their sources')
        return 0
    print()
    for p in problems:
        print('DRIFT: %s' % p)
    print()
    print('Fix: re-run personal/tools/site-manager/export-mcp-data.py and commit the '
          'regenerated datasets. Never hand-edit them.')
    return 0 if WARN_ONLY else 1


if __name__ == '__main__':
    raise SystemExit(main())
